--- #YAML:1.0
name:                     CPAN-Testers-Common-Article
version:                  0.45
abstract:                 Parse a CPAN Testers NNTP article
author:
  - Barbie <barbie@cpan.org>
  - Leon Brocard <leon@astray.com>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Class::Accessor::Fast:  0
  CPAN::DistnameInfo:     0
  Email::Simple:          0
  MIME::Base64:           0
  MIME::QuotedPrint:      0
  Time::Local:            0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  CPAN::Testers::Common::Article:
    file:     lib/CPAN/Testers/Common/Article.pm
    version:  0.45

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Common-Article
  repository: http://github.com/barbie/cpan-testers-common-article

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
